#!/bin/bash

cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")"
cargo test export_bindings_
OUTPUT_PATH="../src-ui/src/host-ui-bridge/generated-bindings.d.ts"
echo "// Generated by src-tauri/generate-bindings.sh. Do not edit manually." > $OUTPUT_PATH
awk '!/generated by/ {print}' bindings/* >> $OUTPUT_PATH
