import { join } from 'path'
import { writeFileSync } from 'fs';
import { labelledFilenames, trueDates } from './client-labels.mjs'
import { extractDates } from "../dates-from-file.mjs";
import { humanize, toMarkdownTable } from "../humanize.mjs";
import { now } from '../dates.mjs';

const pictureDir = "/mnt/c/Users/tfiers/Desktop/voorbeeld-fotos-client"
const path = (filename) => join(pictureDir, filename)

const fileDates = labelledFilenames.map(filename => ({
    filename,
    trueDate: trueDates[filename],
    ...extractDates(path(filename)),
}))
const compareBy = (f) => ((a, b) => f(a) - f(b))
fileDates.sort(compareBy(obj => obj['trueDate'].unix()))

const table = toMarkdownTable(fileDates.map(humanize))

// No `__dirname` & `__filename` in an 'ES module', alas.
const mydir = "picdates/test-data"
const mypath = join(mydir, "main.mjs")

const md = `
${table}

[File generated by \`${mypath}\` on ${now()}]
`
const outPath = join(mydir, "output.md")
writeFileSync(outPath, md)
console.log(`Written [${outPath}]`)
