// Generated by host/generate-bindings.py. Do not edit manually.

export interface Media { path: string, dateTime: string | null, dataUri: string, }

export type MessageToHost = { kind: "addMedia" } | { kind: "changeMediaDateTime", payload: ChangeMediaDateTimePayload, };

export type MessageToUi = { kind: "mediaLoading" } | { kind: "mediaLoadingComplete", payload: MediaLoadingCompletePayload, } | { kind: "mediaLoadingError" };

export interface ChangeMediaDateTimePayload { path: string, newDateTime: string, }

export interface MediaLoadingCompletePayload { newMedia: Array<Media>, }
