// Generated by host/generate-bindings.py. Do not edit manually.

export interface Media { path: string, dateTime: string, dataUri: string, }

export type MessageToHost = { kind: "addMedia" } | { kind: "changeMediaDateTime", path: string, new_date_time: string, };

export type MessageToUi = { kind: "mediaLoading" } | { kind: "mediaLoadingComplete", new_media: Array<Media>, } | { kind: "mediaLoadingError" };
