// Generated by host/generate-bindings.py. Do not edit manually.

export interface LoadMediaPreviewPayload { path: string, }

export interface Media { path: string, dateTime: string | null, }

export type MessageToHost = { kind: "sendLatestMedia" } | { kind: "addMedia" } | { kind: "changeMediaDateTime", payload: ChangeMediaDateTimePayload, } | { kind: "loadMediaPreview", payload: LoadMediaPreviewPayload, };

export type MessageToUi = { kind: "mediaLoading" } | { kind: "mediaLoadingComplete", payload: MediaLoadingCompletePayload, } | { kind: "mediaLoadingError", error: MediaLoadingErrorPayload, } | { kind: "mediaPreviewLoaded", payload: MediaPreviewLoadedPayload, } | { kind: "mediaPreviewLoadError", payload: MediaPreviewLoadErrorPayload, };

export interface MediaLoadingErrorPayload { error: string, }

export interface ChangeMediaDateTimePayload { path: string, newDateTime: string, }

export interface MediaPreviewLoadedPayload { path: string, dataUri: string, }

export interface MediaLoadingCompletePayload { newMedia: Array<Media>, }

export interface MediaPreviewLoadErrorPayload { path: string, error: string, }
