// Generated by src-tauri/generate-bindings.sh. Do not edit manually.

export type ToHostMessage = { kind: "addMedia" } | { kind: "changeMediaDateTime", path: string, new_date_time: string, };

export type ToUiMessage = { kind: "mediaLoading" } | { kind: "mediaLoadingComplete" } | { kind: "mediaLoadingError" };
