#!/usr/bin/env python3

import os, subprocess
from pathlib import Path

BINDINGS_DIR = "bindings"
OUTPUT_PATH = "../ui/src/host-ui-bridge/generated-bindings.d.ts"

os.chdir(os.path.dirname(os.path.abspath(__file__)))
cargo_test_cmd = ["cargo", "test", "export_bindings_"]
cargo_test_res = subprocess.run(cargo_test_cmd)
if cargo_test_res.returncode != 0:
    print(f"Failed to run {cargo_test_cmd}")
    exit(1)

combined_binding_lines = []
for binding_file_path in Path(BINDINGS_DIR).iterdir():
    with open(binding_file_path, "r") as f:
        combined_binding_lines.extend([
            line for line in f.readlines()
            if not (
                line.startswith("// This file was generated by ")
                or line.startswith("import ")
            )
        ][1:])
        combined_binding_lines.append("")
    binding_file_path.unlink()

Path(BINDINGS_DIR).rmdir()

with open(OUTPUT_PATH, "w") as f:
    f.write("// Generated by host/generate-bindings.py. Do not edit manually.\n\n")
    f.write("\n".join(combined_binding_lines))
