name: Continuous Deployment / Release
on:
  push:
    branches-ignore:
      - '**'
      - '!main'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  IMAGE_MAGICK_VERSION: 7.1.0-58

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [
          # TODO: Add gexiv2 macos dependency
          # macos-latest,
          ubuntu-20.04,
          windows-latest
        ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev \
            libayatana-appindicator3-dev librsvg2-dev \
            libx11-dev libxext-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libxml2-dev\
            libgexiv2-dev

      - name: Install ImageMagick 7 (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          wget -O ImageMagick-7.tar.gz \
            "https://download.imagemagick.org/archive/ImageMagick-$IMAGE_MAGICK_VERSION.tar.gz"
          tar -xvf ImageMagick-7.tar.gz
          cd ImageMagick-7
          ./configure
          make -j$(nproc)
          sudo make install
          sudo ldconfig /usr/local/lib
          echo "Version: $(magick -version)"

      - name: Install dependencies (Windows only)
        if: matrix.platform == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gexiv2
            mingw-w64-x86_64-imagemagick

      - name: Set PKG_CONFIG_PATH (Windows only)
        run: |
          echo "PKG_CONFIG_PATH='C:\msys64\mingw64\lib\pkgconfig'" >> $GITHUB_ENV
      
      - name: Test(Windows only)
        run: |
          echo $PKG_CONFIG_PATH
          tree 'C:\msys64'
          
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './host -> target'

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'

      - name: Install UI dependencies
        working-directory: ./ui
        run: npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Picture Date Changer ${{ github.ref_name }}'
          # releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
